data = [
  'PS - PERUMUSAN KEBIJAKAN DI BIDANG STATISTIK MELIPUTI: METODOLOGI DAN INFORMASI STATISTIK, STATISTIK SOSIAL, STATISTIK PRODUKSI, STATISTIK DISTRIBUSI DAN JASA, NERACA DAN ANALISA STATISTIK',
  'PS.000 - Pengkajian dan Pengusulan Kebijakan',
  'PS.100 - Penyiapan Kebijakan',
  'PS.200 - Masukan dan Dukungan dalam Penyusunan Kebijakan.',
  'PS.300 - Pengembangan desain dan standardisasi',
  'PS.400 - Penetapan Norma, Standar, Prosedur dan Kriteria (NSPK)',
  'SS - SENSUS PENDUDUK, SENSUS PERTANIAN DAN SENSUS EKONOMI',
  'SS.000 - PERENCANAAN',
  'SS.010 - Master Plan dan Network planing',
  'SS.020 - Perumusan dan Penyusunan Bahan',
  'SS.021 - Penyiapan bahan penyusunan rancangan sensus',
  'SS.022 - Penyusunan metode pencacahan sensus',
  'SS.023 - Penentuan volume sensus',
  'SS.024 - Penyusunan desain penarikan sampel',
  'SS.025 - Penyusunan Kerangka Sampel',
  'SS.030 - Studi pendahuluan (desk study)',
  'SS.100 - PERSIAPAN SENSUS',
  'SS.110 - Rancangan Organisasi.',
  'SS.120 - Penyusunan Kuesioner.',
  'SS.130 - Penyusunan Konsep dan Definisi.',
  'SS.140 - Penyusunan Metodologi (organisasi, lapangan, ukuran statistik).',
  'SS.150 - Penyusunan Buku Pedoman (pencacahan, pengawasan, pengolahan).',
  'SS.160 - Penyusunan Peta Wilayah Kerja dan Muatan Peta Wilavah.',
  'SS.170 - Penyusunan Pedoman Sosialisasi.',
  'SS.180 - Penyusunan Program Pengolahan (rule validasi pemeriksaan entri tabulasi).',
  'SS.190 - Koordinasi Intern/ Ektern.',
  'SS.200 - PELATIHAN/UJICOBA',
  'SS.210 - Pelatihan Instruktur.',
  'SS.220 - Pelatihan Petugas.',
  'SS.230 - Pelatihan Petugas Pengolahan.',
  'SS.240 - Perancangan Tabel.',
  'SS.250 - Pelaksanaan Ujicoba Kuesioner Sensus (meliputi reliabilitas kuesioner dan sistem pengolahan}.',
  'SS.260 - Pelaksanaan Ujicoba Kuesioner Metodologi Sensus (meliputi ujicoba pelaksanaan pencacahan, organisasi dan jumlah sampel).',
  'SS.300 - PELAKSANAAN LAPANGAN',
  'SS.310 - Listing.',
  'SS.320 - Pemilihan Sampel.',
  'SS.330 - Pengumpulan Data.',
  'SS.340 - Pemeriksaan Data.',
  'SS.350 - Pengawasan Lapangan.',
  'SS.360 - Monitoring Kualitas.',
  'SS.400 - PENGOLAHAN',
  'SS.410 - Pengelolaan Dokumen (penerimaan/pengiriman, pengelompokkan/ batchine:l.',
  'SS.420 - Pemeriksaan Dokumen dan Pengkodean (editing/ coding).',
  'SS.430 - Perekaman Data (entri/scanner).',
  'SS.440 - Tabulasi Data.',
  'SS.450 - Pemeriksaan Tabulasi.',
  'SS.560 - Laporan Konsistensi Tabulasi.',
  'SS.500 - ANALISIS DAN PENYAJIAN HASIL SENSUS',
  'SS.510 - Pembahasan Angka Hasil Pengolahan.',
  'SS.520 - Penyusunan Angka Sementara.',
  'SS.530 - Penyusunan Angka Tetap.',
  'SS.540 - Penyusunan/Pembahasan Draft Publikasi.',
  'SS.550 - Analisis Data Sensus.',
  'SS.560 - Penyusunan Diseminasi Hasil Sensus',
  'SS.600 - DISEMINASI HASIL SENSUS',
  'SS.610 - Penyusun bahan Diseminasi 1) Leaflet, booklet 2) Website 3) Penyusunan CD dan sejenisnya',
  'SS.620 - Sosialisasi hasil Sensus melalui berbagai Media',
  'SS.630 - Layanan Promosi Statistik',
  'VS - SURVEI',
  'VS.000 - PERENCANAAN',
  'VS.010 - Master Plan dan Network planing',
  'VS.020 - Perumusan dan Penyusunan Bahan',
  'VS.021 - Penyiapan bahan penyusunan rancangan survei',
  'VS.022 - Penyusunan metode pencacahan survei',
  'VS.023 - Penentuan volume survei',
  'VS.024 - Penyusunan desain penarikan sampel',
  'VS.025 - Penyusunan Kerangka Sampel',
  'VS.030 - Studi pendahuluan (desk study)',
  'VS.100 - PERSIAPAN SURVEI',
  'VS.110 - Rancangan Organisasi.',
  'VS.120 - Penyusunan  Kuesioner.·',
  'VS.130 - Penyusunan Konsep dan Definisi.',
  'VS.140 - Penyusunan Metodologi (organisasi, lapangan, ukuran statistik).',
  'VS.150 - Penyusunan Buku Pedoman (pencacahan, pengawasan, pengolahan).',
  'VS.160 - Penyusunan Peta Wilayah Kerja dan Muatan Peta Wilayah.',
  'VS.170 - Penyusunan Pedoman Sosialisasi.',
  'VS.180 - Penyusunan Program Pengolahan (rule validasi pemeriksaan entri tabulasi).',
  'VS.190 - Koordinasi Intern/Ektern.',
  'VS.200 - PELATIHAN /UJICOBA',
  'VS.210 - Pelatihan Instruktur.',
  'VS.220 - Pelatihan Petugas.',
  'VS.230 - Pelatihan Petugas Pengolahan.',
  'VS.240 - Perancangan Tabel.',
  'VS.250 - Pelaksanaan Ujicoba Kuesioner survei (meliputi reliabilitas kuesioner dan sistem pengolahan).',
  'VS.260 - Pelaksanaan Ujicoba Kuesioner Metodologi survei (meliputi ujicoba pelaksanaan pencacahan, organisasi dan jumlah sampel).',
  'VS.300 - PELAKSANAAN LAPANGAN',
  'VS.310 - Listing.',
  'VS.320 - Pemilihan Sampel.',
  'VS.330 - Pengumpulan Data.',
  'VS.340 - Pemeriksaan Data.',
  'VS.350 - Pengawasan Lapangan.',
  'VS.360 - Monitoring Kualitas.',
  'VS.400 - PENGOLAHAN',
  'VS.410 - Pengelolaan Dokumen (penerimaan/pengiriman, pengelompokkan/batching).',
  'VS.420 - Pemeriksaan Dokumen dan Pengkodean (editing/ coding).',
  'VS.430 - Perekaman Data (entri/scanner).',
  'VS.440 - Tabulasi Data.',
  'VS.450 - Pemeriksaan Tabulasi.',
  'VS.460 - Laporan Konsistensi Tabulasi.',
  'VS.500 - ANALISIS DAN PENYAJIAN HASIL SURVEI',
  'VS.510 - Pembahasan Angka Hasil Pengolahan.',
  'VS.520 - Penyusunan Angka Sementara.',
  'VS.530 - Penyusunan Angka Proyeksi/Ramalan',
  'VS.540 - Penyusunan Angka Tetap.',
  'VS.550 - Penyusunan/ Pembahasan Draft Publikasi.',
  'VS.560 - Analisis Data Survei.',
  'VS.570 - Penyusunan Diseminasi Basil Survei.',
  'VS.600 - DISEMINASI BASIL SURVEI',
  'VS.610 - Penyusun bahan Diseminasi 1) Leaflet, booklet 2) Website 3) Penyusunan CD dan sejenisnya',
  'VS.620 - Sosialisasi hasil Survei melalui berbagai Media',
  'VS.630 - Layanan Promosi Statistik',
  'KS - KONSOLIDASI  DATA STATISTIK',
  'KS.000 - KOMPILASI DATA',
  'KS.100 - ANALISIS DATA',
  'KS.200 - PENYUSUNAN PUBLIKASI',
  'ES - EVALUASI DAN PELAPORAN SENSUS, SURVEI DAN KONSOLIDASI DATA',
  'KU - KEUANGAN',
  'KU.000 - PELAKSANAAN ANGGARAN',
  'KU.010 - Ketentuan/ Peraturan Menteri Keuangan Menyangkut Pelaksanaan dan Penatausahaan.',
  'KU.100 - REALISASI PENDAPATAN/PENERIMAAN NEGARA',
  'KU.110 - Surat Setoran Pajak (SSP).',
  'KU.120 - Surat Setoran Bukan Pajak (SSBP).',
  'KU.130 - Bukti Penerimaan Bukan Pajak (PNBP).',
  'KU.140 - Dana Bagi Hasil yang bersumber dari Pajak:',
  'KU.141 - Pajak Bumi Bangunan.',
  'KU.142 - Bea Perolehan Hak Atas Tanah dan Bangunan (BPHTB).',
  'KU.143 - Pajak Penghasilan (Pph) Pasal 21, 25 dan 29.',
  'KU.150 - Bukti Setor Sisa Anggaran Lebih atau Bukti Setor Pengembalian Belanja (SSPB).',
  'KU.160 - Bunga dan/atau Jasa Giro pada Bank.',
  'KU.170 - Piutang Negara.',
  'KU.180 - Pengelolaan Investasi dan Penyertaan Modal.',
  'KU.200 - PENGELOLAAN PERBENDAHARAAN',
  'KU.210 - Pejabat Penguji dan Penandatanganan SPM.',
  'KU.220 - Bendahara Penerimaan.',
  'KU.230 - Bendahara Pengeluaran.',
  'KU.240 - Kartu Pengawasan Pembayaran Penghasilan Pegawai (KP4).',
  'KU.250 - Pengembalian Belanja.',
  'KU.260 - Pembukuan Anggaran:',
  'KU.261 - Buku Kas Umum (BKU).',
  'KU.262 - Buku Kas Pembantu.',
  'KU.263 - Kartu Realisasi Anggaran dan Pengawasan Realisasi Anggaran.',
  'KU.270 - Berita Acara Pemeriksanaan Kas.',
  'KU.280 - Daftar Gaji/Kartu Gaji.',
  'KU.300 - PENGELUARAN ANGGARAN Naskah-naskah yang berkaitan dengan pelaksanaan anggaran pengeluaran mulai dari SPP-GU, SPP-LS, SPP-UP, SPP-UP,SPP-TUP, 8PM, SP2D, Juklak mekanisme pengelolaan APBN serta bahan nota keuangan',
  'KU.310 - Belanja Bahan.',
  'KU.320 - Belanja Barang.',
  'KU.330 - Belanja Jasa (Konsultan, Profesi).',
  'KU.340 - Belanja Perjalanan.',
  'KU.350 - Belanja Pegawai.',
  'KU.360 - Belanja Paket Meeting Dalam Kota.',
  'KU.370 - Belanja Paket Meeting Luar Kota.',
  'KU.380 - Belanja Akun Kombinasi.',
  'KU.400 - VERIFIKASI ANGGARAN',
  'KU.410 - Surat Permintaan Pembayaran (SPP) beserta lampirannya.',
  'KU.420 - Surat Perintah Membayar (SPM), Surat perintah Pencairan dana (SP2D).',
  'KU.500 - PELAPORAN',
  'KU.510 - Akuntansi Keuangan:',
  'KU.511  - Berita Acara Pemeriksaan Kas',
  'KU.512  - Kas/Register Penutupan Kas.',
  'KU.513 - Laporan Pendapatan Negara.',
  'KU.514  - Arsip Data Komputer (ADK).',
  'KU.520 - Pengumpulan, Pemantauan, Evaluasi dan Laporan Keuangan:',
  'KU.521 - Keadaan Kredit Anggaran (LKKA) Bulanan/ Triwulanan/ Semesteran a.   Laporan Realisasi Anggaran (RKA); b.  Neraca; c.   Laporan Arus Kas; d.   Catatan Atas Laporan Keuangan (CALK)',
  'KU.530 - Rekonsiliasi Data Laporan Keuangan.',
  'KU.600 - BANTUAN PINJAMAN LUAR NEGERI',
  'KU.610 - Permohonan Pinjaman Luar Negeri (Blue Book).',
  'KU.620 - Dokumen Kesanggupan negara donor (Gray Book).',
  'KU.630 - Memorandum of Understand (MOU) dan dokumen sejenisnya.',
  'KU.640 - Loan Agreement Pinjaman/Hibah Luar Negeri (PHLN), legal opinion, surat-menyurat dengan lender, konsultan.',
  'KU.650 - Alokasi dan Relokasi Penggunaan Dana Pinjaman/Hibah Luar Negeri.',
  'KU.660 - Penarikan Dana Bantuan Luar Negeri (BLN).',
  'KU.661 - Aplikasi Penarikan Dana Bantuan Luar Negeri (BLN) berikut lampirannya: a.  Reimbursment; b.  Direct Payment/ Transfer Procedure; C. Special Comitment/ LI C Opening; d. Special Account/ Imprest Fund.',
  'KU.662 - Otorisasi Penarikan Dana (Payment Advice).',
  'KU.663 - Replenisment (permintaan penarikan dana dari negara donor) meliputi: a. No Objection Letter (NOL); b. Notification of Contract; C. Withdrawal Authorization (WA); d.  Statement of Expenditur (SE).',
  'KU.670 - Realisasi Pencairan Dana Bantuan Luar Negeri: a.  Surat Perintah Pencairan Dana (SP2D) b. SPM beserta lampirannya: SPP, Kontrak, BA dan data pendukung lainnya.',
  'KU.680 - Ketentuan/Peraturan yang Menyangkut Bantuan/Pinjaman Luar Negeri.',
  'KU.690 - Laporan-Laporan Pelaksanaan Bantuan/Pinjaman Luar Negeri.',
  'KU.691 - Staff Appraisal Report.',
  'KU.692 - Report/Laporan yang terdiri dari: a. Progress Report; b. Monthly Report; C. Quartely Report.',
  'KU.693 - Laporan Hutang Negara: a.  Laporan Pembayaran Hutang Negara; b. Laporan Posisi Hutang Negara.',
  'KU.694 - Completion Report/ Annual Report.',
  'KU.700 - PENGELOLA APBN/DANA PINJAMAN/HIBAH LUAR NEGERI (PHLN)',
  'KU.710 - Keputusan Kepala BPS tentang Penetapan:',
  'KU.711 - Kuasa Pengguna Anggaran (KPA), Pejabat Pembuat Komitmen (PPK);',
  'KU.712 - Pejabat Pembuat Daftar Gaji ;',
  'KU.713 - Penandatangan SPM;',
  'KU.714 - Bendahara Penerimaan/Pengeluaran, Pengelola Barang.',
  'KU.800 - SISTEM AKUNTANSI INSTANSI (SAI)',
  'KU.810 - Manual Implementasi Sistem Akuntansi Instansi (SAI).',
  'KU.820 - Arsip Data Komputer dan Berita Acara Rekonsiliasi.',
  'KU.830 - a. Daftar Transaksi (DT), Pengeluaran (PK), Penerimaan (PN). b. Dokumen Sumber (DS), Bukti Jurnal (BJ) Surat Tanda Setor (STS). c. Surat Setor Bukan Pajak (SSBP), Surat Perintah Pencairan Dana (SP2D). d. SPM dalam Daftar Ringkasan Pengembalian dan Potongan dari Pengeluaran (SPDR).',
  'KU.840 - Listing (Daftar Rekaman Penerimaan) Buku Temuan dan Tindakan Lain (SAi).',
  'KU.850 - Laporan Realisasi Bulanan SAi.',
  'KU.860 - Laporan Realisasi Triwulanan SAi dari Unit Akuntansi Wilayah (UAW) dan Gabungan semua UAW /Unit Akuntansi Kantor Pusat Instansi (UAKPI).',
  'KU.900 - PERTANGGUNGJAWABAN KEUANGAN NEGARA',
  'KU.910 - Laporan Hasil Pemeriksaan atas Laporan Keuangan oleh BPK RI.',
  'KU.920 - Hasil Pengawasan dan Pemeriksaan Internal.',
  'KU.930 - Laporan Aparat Pemeriksa Fungsional:',
  'KU.931 - Laporan Hasil Pemeriksaan (LHP).',
  'KU.932 - Memorandum Hasil Pemeriksaaan (MHP).',
  'KU.933 - Tindak Lanjut/Tanggapan LHP.',
  'KU.940 - Dokumentasi Penyelesaian Keuangan Negara:',
  'KU.941 - Tuntutan Perbendaharaan.',
  'KU.942 - Tuntutan Ganti Rugi.',
  'KP - KEPEGAWAIAN',
  'KP.000 - FORMASI PEGAWAI',
  'KP.010 - Usulan dari Unit Kerja.',
  'KP.020 - Usulan Permintaan Formasi kepada Menpan dan KepalaBKN.',
  'KP.030 - Persetujuan Menpan.',
  'KP.040 - Penetapan Formasi.',
  'KP.050 - Penetapan Formasi Khusus.',
  'KP.100 - PENGADAAN DAN PENGANGKATAN PEGAWAI',
  'KP.110 - Proses Penerimaan Pegawai:',
  'KP.111 - Pengumuman.',
  'KP.112 - Seleksi Administrasi.',
  'KP.113 - Pemanggilan Peserta Tes.',
  'KP.114 - Pelaksanaan Ujian (tertulis, psikotes, wawancara).',
  'KP.115 - Keputusan Hasil Ujian.',
  'KP.120 - Penetapan Pengumuman Kelulusan.',
  'KP.130 - Berkas Lamaran yang Tidak Diterima.',
  'KP.140 - Nota Usul dan Kelengkapan Penetapan NIP.',
  'KP.150 - Nota Usul Pengangkatan CPNS menjadi PNS.',
  'KP.160 - Nota Usul Pengangkatan CPNS menjadi PNS Lebih 2 Tahun.',
  'KP.170 - SK CPNS/PNS Kolektif.',
  'KP.200 - BERKAS PEGAWAI TIDAK TETAP/MITRA STATISTIK',
  'KP.300 - PEMBINAAN KARIR PEGAWAI',
  'KP.310 - Diklat Kursus/Tugas Belajar /Ujian Dinas/Izin Belajar Pegawai:',
  'KP.311 - Surat Perintah/Surat Tugas/SK/Surat Izin.',
  'KP.312 - Laporan Kegiatan Pengembangan Diri.',
  'KP.313 - Surat Tanda Tamat Pendidikan dan Pelatihan.',
  'KP.320 - Ujian Kompetensi',
  'KP.321 - Assesment Tes Pegawai.',
  'KP.322 - Pemetaan/ Mapping Talent Pegawai.',
  'KP.330 - Daftar Penilaian Pelaksanaan Pekerjaan (DP3) dan Sasaran Kinerja Pegawai (SKP).',
  'KP.340 - Pakta Integritas Pegawai.',
  'KP.350 - Laporan Hasil Kekayaan Penyelenggaraan Negara (LHKPN).',
  'KP.360 - Daftar Usul Penetapan Angka Kredit Fungsional.',
  'KP.370 - Disiplin Pegawai:',
  'KP.371 - Daftar Hadir.',
  'KP.372 - Rekapitulasi Daftar Hadir.',
  'KP.380 - Berkas Hukuman Disiplin.',
  'KP.390 - Penghargaan dan Tanda Jasa (Satya Lencana/Bintang Jasa).',
  'KP.400 - PENYELESAIAN PENGELOLAAN KEBERATAN PEGAWAI',
  'KP.500 - MUTASI PEGAWAI',
  'KP.510 - Alih Status, Pindah Instansi, Pindah Wilayah Kerja, Diperbantukan, Dipekerjakan, Penugasan Sementara, Mutasi Antar Perwakilan, Mutasi ke dan dari perwakilan Sementara, Mutasi Antar Unit.',
  'KP.520 - Nota Persetujuan/Pertimbangan Kepala BKN.',
  'KP.530 - Mutasi Keluarga:',
  'KP.531 - Surat Izin Pernikahan/Perceraian.',
  'KP.532 - Surat Penolakan Izin Pernikahan/Perceraian.',
  'KP.533 - Akte Nikah/Cerai.',
  'KP.534 - Surat Keterangan Meninggal Dunia.',
  'KP.540 - Usul Kenaikan Pangkat/Golongan/Jabatan.',
  'KP.550 - Usul Pengangkatan dan Pemberhentian dalam Jabatan Struktural/ Fungsional.',
  'KP.560 - Usul Penetapan Perubahan Data Dasar/ Status/Kedudukan Hukum Pegawai.',
  'KP.570 - Peninjauan Masa Kerja.',
  'KP.580 - Berkas Baperjakat.',
  'KP.600 - ADMINISTRASI PEGAWAI',
  'KP.610 - Dokumentasi Identitas Pegawai:',
  'KP.611 - Usul Penetapan Karpeg/ KPE /Karls/ Karsu.',
  'KP.612 - Keanggotaaan Organisasi Profesi/Kedinasan:',
  'KP.613 - Laporan Pajak Penghasilan Pribadi (LP2P).',
  'KP.614 - Keterangan Penerimaan Penghasilan Pegawai (KP4).',
  'KP.620 - Berkas Kepegawaian dan Daftar Urut Kepangkatan (DUK).',
  'KP.630 - Berkas Perorangan Pegawai Negeri Sipil: a. Nota Penetapan NIP dan kelengkapannya;b. Nota Persetujuan/Pertimbangan Kepala BKN;c. SK Pengangkatan CPNS;d. Hasil Pengujian Kesehatan;e. SK Pengangkatan PNS;f. SK Peninjauan Masa Kerja;g. SK Kenaikan Pangkat;h. Surat Pernyataan Melaksanakan Tugas, Menduduki Jabatan/Surat Pernyatatm Pelantikan;i. SK Pengangkatan Dalam atau Pemberhentian Dari Jabatan Struktural/Fungsional;j. SK Perpindahan Wilayah Kerja;k. SK Perpindahan Antar lnstansi;1. SK Cuti di Luar Tanggungan Negara (CLTN);m. Berita Acara Pemeriksaan;n. SK Hukuman Jabatan/Hukuman Disiplin PNS;o. SK Perbantuan/Dipekerjakan Diluar Instansi Induk;p. SK Penarikan Kembali dan Perbantuan/ Dipekerjakan;q. SK Pemberian Uang Tunggu;r. SK Pembebasan Dari Jabatan Organik Karena Diangkat Sebagai Pejabat Negara;s.  SK Pengalihan PNS;t. SK Pemberhentian Sebagai PNS;u. SK Pemberhentian Sementara;v.  Surat Keterangan Pernyataan Hilang;w. Surat Keterangan Kembalinya PNS Yang Dinyatakan Hilang;x.  SK Penggantian Nama;y. Surat Perbaikan Tanggal Tahun Kelahiran;z.  Akta Nikah/ Cerai;aa. Akta Kelahiran;bb. Isian Formulir PUPNS;cc. Berita Acara Pengambilan Sumpah/Janji PNS dari Jabatan;dd.  Surat Permohonan Menjadi Anggota Parpol;ee. Surat Keterangan Mutasi Keluarga;ff. Surat Keterangan Meninggal Dunia;gg. Surat Keterangan Peningkatan Pendidikan;hh. Penetapan Angka Kredit Jabatan Fungsional;ii. Surat Keterangan Hasil Penelitian Khusus;JJ. Surat Pemberitahuan Kenaikan Gaji Berkala;kk. Surat Tugas/Izin Belajar Dalam/Luar Negeri;II. Surat Izin Bepergian ke Luar Negeri;mm. Kartu Pendaftaran Ulang (Kardaf) PNS;nn. Ijasah/ Sertifikat;00. SK Penempatan/Penarikan Pegawai;pp. SK Pengangkatan Pada Jabatan Diluar Instansi Induk;qq. Surat Pertimbangan Status TNI;rr. SK Pengaktifan Kembali Sebagai PNS;ss. Surat Pernyataan Pengunduran Diri Dari Jabatan Organik Karena Dicalonkan Sebagai Kepala/Wakil Kepala Daerah.',
  'KP.640 - Berkas Perseorangan Pejabat Negara:',
  'KP.641 - Kepala BPS;',
  'KP.642 - Pejabat Negara Lain yang ditentukan oleh Undang-Undang;',
  'KP.650 - Surat Perintah Dinas/Surat Tugas.',
  'KP.660 - Berkas Cuti Pegawai:',
  'KP.661 - Cuti Sakit.',
  'KP.662 - Cuti Bersalin.',
  'KP.663 - Cuti Tahunan.',
  'KP.664 - Cuti Alasan Penting.',
  'KP.665 - Cuti Luar Tanggungan Negara (CTLN).',
  'KP.700 - KESEJAHTERAAN PEGAWAI',
  'KP.710 - Berkas Tentang Layanan Tunjangan/Gaji.',
  'KP.720 - Berkas Tentang Layanan Pemeliharaan Kesehatan Pegawai.',
  'KP.730 - Berkas Tentang Layanan Asuransi Pegawai.',
  'KP.740 - Berkas Tentang Layanan Bantuan Sosial.',
  'KP.750 - Berkas Tentang Layanan Olahraga Dan Rekreasi.',
  'KP.760 - Berkas Tentang Layanan Pengurusan Jenasah.',
  'KP.770 - Berkas Tentang Layanan Organisasi Non Kedinasan (Korpri, Dharma Wanita, Koperasi).',
  'KP.800 - PEMBERHENTIAN PEGAWAI TANPA HAK PENSIUN',
  'KP.900 - USUL PEMBERHENTIAN DAN PENETAPAN PENSIUN PEGAWAI/ JANDA/DUDA & PNS YANG TEWAS',
  'PR - PERENCANAAN',
  'PR.000 - POKOK-POKOK KEBIJAKAN DAN STRATEGI PEMBANGUNAN',
  'PR.010 - Pengumpulan Data.',
  'PR.020 - Rencana Pembangunan Jangka Panjang (RPJP).',
  'PR.030 - Rencana Pembangunan Jangka Panjang (RPJP).',
  'PR.040 - Rencana Kerja Pemerintah (RKP).',
  'PR.050 - Penyelenggaraan Musyawarah Perencanaan Pembangunan (Musrenbang).',
  'PR.100 - PENYUSUNAN RENCANA',
  'PR.110 - Rencana Kegiatan Teknis.',
  'PR.120 - Rencana Kegiatan Non Teknis.',
  'PR.130 - Keterpaduan Rencana Teknis dan Non teknis.',
  'PR.200 - PROGRAM KERJA TAHUNAN',
  'PR.210 - Usulan Unit Kerja beserta data pendukungnya.',
  'PR.220 - Program Kerja Tahunan Unit Kerja.',
  'PR.230 - Program Kerja Tahunan lnstansi/Lembaga.',
  'PR.300 - RENCANA ANGGARAN PENDAPATAN DAN BELANJA NEGARA (RAPBN)',
  'PR.310 - Penyusunan  RAPBN',
  'PR.311 - Arah kebijakan Umum, Strategi, Prioritas dan Renstra: a.  Rencana Kerja; b. Rencana Kerja Pemerintah.',
  'PR.312 - Rencana Kerja dan Anggaran Kementrian/ Lembaga (RKAKL).',
  'PR.313 - Rencana Satuan Anggaran Per Satuan Kerja (SAPSK), Satuan Rincian Alokasi Anggaran (SRAA).',
  'PR.320 - Penyampaian APBN kepada DPR RI',
  'PR.321 - Nota Keuangan pemerintah dan Rancangan Undang-Undang RAPBN: a. Nota Keuangan Pemerintah; b. Materi RAPBN dari Lembaga Negara dan Badan Pemerintah (RASKIP).',
  'PR.322 - Pembahasan RAPBN oleh Komisi DPR RI.',
  'PR.323 - Risalah Rapat Dengar Pendapat dengan DPR RI.',
  'PR.324 - Nota Jawaban DPR RI.',
  'PR.330 - Undang-Undang Anggaran pendapatan dan Belanja Negara (APBN) dan Rencana Pembangunan Tahunan (REPETA).',
  'PR.400 - PENYUSUNAN ANGGARAN PENDAPATAN NEGARA (APBN)',
  'PR.410 - Ketetapan Pagu Indikatif/Pagu Sementara.',
  'PR.420 - Ketetapan Pagu Definitif.',
  'PR.430 - Rencana Kerja Anggaran (RKA) Lembaga Negara dan Badan Pemerintah (LNBP).',
  'PR.440 - Daftar Isian Pelaksanaan Anggaran (DIPA) dan Revisinya.',
  'PR.450 - Petunjuk Operasional Kegiatan (POK) dan  Revisinya.',
  'PR.460 - Petunjuk Teknis Tata Laksana Keterpaduan Kegiatan dan Pengelolaan Anggaran.',
  'PR.470 - Target Penerimaan Negara Bukan Pajak.',
  'PR.500 - PENYUSUNAN STANDAR HARGA MONITORING PROGRAM',
  'PR.510 - Pedoman Pengumpulan dan Pengolahan Data Standar Harga.',
  'PR.520 - Pedoman Teknis Monitoring Program dan Kegiatan.',
  'PR.530 - Pedoman Teknis Evaluasi dan Pelaporan Program.',
  'PR.600 - LAPORAN',
  'PR.610 - Laporan Khusus.',
  'PR.611 - Pemantauan Prioritas.',
  'PR.612 - Laporan Pelaksanaan Kegiatan Atas Permintaan Eksternal.',
  'PR.613 - Laporan Atas Pelaksanaan Kegiatan/Program Tertentu.',
  'PR.614 - Rapat Dengar Pendapat dengan DPR RI.',
  'PR.620 - Laporan Progress Report.',
  'PR.630 - Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP).',
  'PR.640 - Laporan Berkala (harian, mingguan, bulanan, triwulanan, semesteran, tahunan).',
  'PR.700 - EVALUASI PROGRAM',
  'PR.710 - Evaluasi Program Unit Kerja.',
  'PR.720 - Evaluasi Program Lembaga/lnstansi.',
  'HK - HUKUM',
  'HK.000 - PROGRAM LEGISLASI',
  'HK.010 - Bahan/Materi Program Legislasi Nasional dan Instansi.',
  'HK.020 - Program Legislasi Lembaga/Instansi.',
  'HK.100 - PERATURAN PIMPINAN LEMBAGA/INSTANSI - Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum.',
  'HK.110 - Peraturan Kepala BPS.',
  'HK.200 - KEPUTUSAN/KETETAPAN PIMPINAN LEMBAGA/INSTANSI - Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum.',
  'HK.300 - INSTRUKSI SURAT EDARAN - Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum.',
  'HK.310 - Instruksi/Surat Edaran Kepala BPS.',
  'HK.320 - lnstruksi/Surat Edaran Pejabat Tinggi Madya dan Pejabat Tinggi Pratama.',
  'HK.400 - SURAT PERINTAH',
  'HK.410 - Surat Perintah Kepala BPS.',
  'HK.420 - Surat Perintah Pejabat Madya.',
  'HK.430 - Surat Perintah Pejabat Pratama.',
  'HK.500 - PEDOMAN - Standar /Pedoman/Prosedur Kerja/Petunjuk Pelaksanaan/Petunjuk Teknis yang Bersifat Nasional/Regional/Instansional termasuk rancangan awal sampai dengan rancangan akhir.',
  'HK.600 - NOTA KESEPAHAMAN',
  'HK.610 - Dalam Negeri.',
  'HK.620 - Luar Negeri.',
  'HK.700 - DOKUMENTASI HUKUM - Undang-undang Peraturan Pemerintah, Keputusan Presiden dan peraturan-peraturan lain di luar produk hukum BPS yang dijadikan referensi.',
  'HK.800 - SOSIALISASI/PENYULUHAN /PEMBINAAN HUKUM',
  'HK.810 - Berkas yang berhubungan dengan kegiatan sosialisasi atau penyuluhan hukum',
  'HK.820 - Laporan hasil pelaksanaan sosialisasi penyuluhan hukum',
  'HK.900 - BANTUAN KONSULTASI HUKUM/ ADVOKASI - Berkas tentang pemberian bantuan/konsultasi hukum (Pidana, Perdata, Tata Usaha Negara, dan Agama).',
  'HK.1000 - KASUS/SENGKETA HUKUM',
  'HK.1010 - Pidana - Berkas tentang kasus/sengketa pidana, baik kejahatan maupun pelanggaran:',
  'HK.1011 - Proses verbal mulai dari penyelidikan, penyidikan sampai dengan vonis.',
  'HK.1012 - Berkas pembelaan dan bantuan hukum',
  'HK.1013 - Telaah hukum dan opini hukum.',
  'HK.1020 - Perdata',
  'HK.1021 - Proses gugatan sampai dengan putusan.',
  'HK.1022 - Berkas pembelaan dan bantuan hukum.',
  'HK.1023 - Telaah hukum dan opini hukum',
  'HK.1030 - Tata Usaha Negara',
  'HK.1031 - Proses gugatan sampai dengan putusan.',
  'HK.1032 - Berkas pembelaan dan bantuan hukum.',
  'HK.1033 - Telaah hukum dan opini hukum.',
  'HK.1040 - Arbitrase',
  'HK.1041 - Proses gugatan sampai dengan putusan.',
  'HK.1042 - Berkas pembelaan dan bantuan hukum',
  'HK.4013 - Telaah hukum dan opini hukum.',
  'OT - ORGANISASI DAN TATA LAKSANA',
  'OT.000 - ORGANISASI - Meliputi hal-hal yang berkenaan dengan masalah bahan persipan dan penyusunan organisasi BPS dan unit kerja dibawahnya.',
  'OT.010 - Pembentukan Organisasi.',
  'OT.020 - Pengubahan Organisasi.',
  'OT.030 - Pembubaran Organisasi.',
  'OT.040 - Evaluasi Kelembagaan: Meliputi naskah-naskah yang berkaitan dengan penilaian dan penyempurnaan organisasi.',
  'OT.050 - Uraian Jabatan: Meliputi hal-hal yang berkenaan dengan masalah klasifikasi kepegawaian/pekerjaan, penelitian, jabatan dan analisa jabatan',
  'OT.100 - TATA LAKSANA',
  'OT.110 - Standar Kompetensi Jabatan Struktural dan Fungsional. Meliputi hal-hal yang berkenaan dengan standar kompetensi jabatan struktural dan jabatan fungsional.',
  'OT.120 - Tata Hubungan Kerja: Meliputi hal-hal berkenaan dengan masalah penyusunan tata hubungan kerja baik intern maupun ekstern BPS',
  'OT.130 - Sistem dan Prosedur: Meliputi hal-hal berkenaan dengan masalah penelaahan tata cara dan metode kegiatan di bidang perstatistikan.',
  'HM - HUBUNGAN MASYARAKAT',
  'HM.000 - KEPROTOKOLAN',
  'HM.010 - Penyelenggaraan acara kedinasan (upacara, pelantikan, peresmian dan jamuan termasuk acara peringatan hari­ hari besar).',
  'HM.020 - Agenda kegiatan pimpinan .',
  'HM.030 - Kunjungan dinas:',
  'HM.031 - Kunjungan dinas dalam dan luar negeri.',
  'HM.032 - Kunjungan dinas pimpinan lembaga/instansi.',
  'HM.033 - Kunjungan dinas pejabat lain/ pegawai.',
  'HM.040 - Buku tamu.',
  'HM.050 - Daftar nama/ alamat kantor/ pejabat.',
  'HM.100 - LIPUTAN MEDIA MASSA - Liputan kegiatan dinas pimpinan acara kedinasan dan peristiwa-peristiwa bidang masing-masing yang diliput oleh media massa (cetak dan elektronik).',
  'HM.200 - PENYAJIAN INFORMASI KELEMBAGAAN - Penyajian informasi kelembagaan, pengumpulan, pengolahan dan penyajian informasi kelembagaan.',
  'HM.210 - Kliping Koran.',
  'HM.220 - Penerbitan majalah, buletin, koran dan jurnal.',
  'HM.230 - Brosur/leaflet/poster/ plakat. ',
  'HM.240 - Pengumuman/ pemberitaan.',
  'HM.300 - HUBUNGAN ANTAR LEMBAGA',
  'HM.310 - Hubungan antar lembaga pemerintah.',
  'HM.320 - Hubungan dengan organisasi sosial/LSM.',
  'HM.330 - Hubungan dengan perusahaan.',
  'HM.340 - Hubungan dengan perguruan tinggi/ sekolah: magang, Pendidikan Sistem Ganda, Praktek Kerja Lapangan (PKL).',
  'HM.350 - Forum Kehumasan (Bakohumas/Perhumas).',
  'HM.360 - Hubungan dengan media massa: a. Siaran pers/konferensi pers/pers release; b. Kunjungan wartawan/peliputan; c. Wawancara.',
  'HM.400 - DENGAR PENDAPAT/HEARING DPR',
  'HM.500 - PENYIAPAN BAHAN MATER! PIMPINAN',
  'HM.600 - PUBLIKASI MELALUI MEDIA CETAK MAUPUN ELEKTRONIK',
  'HM.700 - PAMERAN / SAYEMBARA/LOMBA/FESTIVAL, PEMBUATAN SPANDUK DAN IKLAN',
  'HM.800 - PENGHARGAAN/KENANG-KENANGAN/CINDERA MATA',
  'HM.900 - UCAPAN TERIMA KASIH, UCAPAN SELAMAT, BELA SUNGKAWA, PERMOHONAN MAAF',
  'KA - KEARSIPAN',
  'KA.000 - PENCETAKAN',
  'KA.010 - Penyiapan pembuatan buku kerja dan kalender BPS.',
  'KA.020 - Penerimaan permintaan mencetak dan naskah yang akan dicetak.',
  'KA.030 - Menyusun perencanaan cetak.',
  'KA.040 - Pencetakan naskah, surat, dokumen secara digital dan risograph.',
  'KA.100 - PENGURUSAN SURAT',
  'KA.110 - Surat Masuk/Surat Keluar.',
  'KA.120 - Penggunaan Aplikasi Surat Menyurat.',
  'KA.200 - PENGELOLAAN ARSIP DINAMIS',
  'KA.210 - Penyusunan Sistem Arsip.',
  'KA.220 - Penciptaan dan Pemberkasan Arsip.',
  'KA.230 - Pengolahan Data Base menjadi Informasi.',
  'KA.240 - Alih Media.',
  'KA.300 - PENYIMPANAN DAN PEMELIHARAAN ARSIP',
  'KA.310 - Daftar Arsip.',
  'KA.320 - Pemeliharaan Arsip dan Ruang Penyimpanan (seperti kegiatan fumigasi).',
  'KA.330 - Daftar Pencarian Arsip.',
  'KA.340 - Daftar Arsip Informasi Publik.',
  'KA.350 - Daftar Arsip Vital/ Aset.',
  'KA.360 - Layanan Arsip (peminjam, pengguna arsip).',
  'KA.370 - Persetujuan Jadwal Retensi Arsip.',
  'KA.400 - PEMINDAHAN ARSIP',
  'KA.410 - Pemindahan Arsip Inaktif.',
  'KA.420 - Daftar Arsip yang Dipindahkan.',
  'KA.500 - PEMUSNAHAN ARSIP YANG TIDAK BERNILAI GUNA',
  'KA.510 - Berita Acara Pemusnahan.',
  'KA.520 - Daftar Arsip yang Dimusnahkan.',
  'KA.530 - Rekomendasi/Pertimbangan/Pemusnahan Arsip dari ANRI.',
  'KA.540 - Surat Keputusan Pemusnahan.',
  'KA.600 - PENYERAHAN ARSIP STATIS',
  'KA.610 - Berita Acara Serah Terima Arsip.',
  'KA.620 - Daftar Arsip yang Diserahkan.',
  'KA.700 - PEMBINAAN KEARSIPAN',
  'KA.710 - Pembinaan Arsiparis.',
  'KA.720 - Apresiasi/ Sosialisasi/ Penyuluhan Kearsipan, Diklat Profesi.',
  'KA.730 - Bimbingan Teknis',
  'KA.740 - Penilaian dan sertifikasi SDM kearsipan',
  'KA.750 - Supervisi dan Monitoring',
  'KA.760 - Penilaian dan Akreditasi Unit Kerja Kearsipan',
  'KA.770 - Implementasi Pengelolaan Arsip Elektronik',
  'KA.780 - Penghargaan Kearsipan',
  'KA.790 - Pengawasan Kearsipan',
  'RT - KERUMAHTANGGAAN',
  'RT.000 - TELEKOMUNIKASI - Administrasi penggunaan/langganan peralatan telekomunikasi meliputi: telepon, radio, teleks, TV kabel dan internet.',
  'RT.100 - ADMINISTRASI PENGGUNAAN FASILITAS KANTOR - Administrasi penggunaan fasilitas kantor meliputi permintaan dan penggunaan ruang, gedung, kendaraan, wisma rumah dinas, dan fasilitas kantor lainnya.',
  'RT.200 - PENGURUSAN KENDARAAN DINAS',
  'RT.210 - Pengurusan Surat Kendaraan Dinas.',
  'RT.220 - Pemeliharaan dan Perbaikan.',
  'RT.230 - Pengurusan Kehilangan dan Masalah Kendaraan.',
  'RT.300 - PEMELIHARAAN GEDUNG DAN TAMAN',
  'RT.310 - Pertamanan / Lanscaping.',
  'RT.320 - Penghijauan.',
  'RT.330 - Perbaikan Gedung.',
  'RT.340 - Perbaikan Rumah Dinas/Wisma.',
  'RT.350 - Kebersihan Gedung dan Taman.',
  'RT.400 - PENGELOLAAN JARINGAN LISTRIK, AIR, TELEPON DAN KOMPUTER',
  'RT.410 - Per baikan / Pemeliharaan.',
  'RT.420 - Pemasangan.',
  'RT.500 - KETERTIBAN DAN KEAMANAN',
  'RT.510 - Pengamanan, penjagaan dan pengawasan terhadap pejabat, kantor, dan rumah dinas:',
  'RT.511 - Daftar Nama Satuan Pengamanan.',
  'RT.512 - Daftar Jaga/Daftar Piket.',
  'RT.513 - Surat Ijin Keluar Masuk Orang atau Barang.',
  'RT.520 - Laporan Ketertiban dan Keamanan:',
  'RT.521 - Kehilangan, kerusakan, kecelakaaan, gangguan.',
  'RT.600 - ADMINISTRASI PENGELOLAAN PARKIR',
  'PL - PERLENGKAPAN',
  'PL.000 - Rencana Kebutuhan Barang dan Jasa',
  'PL.010 - Usulan Unit Kerja',
  'PL.020 - Rencana Kebutuhan lembaga Pusat/Daerah',
  'PL.100 - Berkas Perkenalan',
  'PL.200 - Pengadaan Barang',
  'PL.210 - Pengadaan/pembelian barang tidak melalui lelang (pengadaan langsung): -   Usulan unit kerja, -   Proses pengadaan barang, -   Serah terima barang',
  'PL.220 - Pengadaan/pembelian barang melalui lelang: - Umum - Terbatas - Pemilihan Langsung - Serah terima barang',
  'PL.230 - Perolehan barang melalui bantuan/hibah',
  'PL.240 - Pengadaan barang melalui tukar menukar',
  'PL.250 - Pemanfaatan barang melalui pinjam pakai',
  'PL.260 - Pemanfaatan barang melalui sewa',
  'PL.270 - Pemanfaatan barang melalui kerjasama pemanfaatan',
  'PL.280 - Pemanfaatan barang melalui bangun serah guna/bangun serah guna',
  'PL.300 - Pengadaan Jasa - Berkas pengadaan jasa oleh pihak ketiga terdiri dari berkas penawaran sampai dengan kontrak perjanjian',
  'PL.400 - Laporan kemajuan pelaksanaan belanja modal',
  'PL.500 - INVENTARISASI',
  'PL.510 - Inventarisasi Ruangan/ Gedung/Bangunan.',
  'PL.511 - Daftar Inventaris Ruangan (DIR)',
  'PL.512 - Buku Inventaris/Pembantu Inventaris Ruangan',
  'PL.520 - Inventarisasi Barang.',
  'PL.521 - Daftar Opname Fisik Barang Inventaris ( (DOFBI)',
  'PL.522 - Daftar lnventaris Barang (DIB)',
  'PL.523 - Daftar Kartu Inventaris Barang',
  'PL.524 - Buku Inventaris/Pembantu Inventaris Barang',
  'PL.530 - Penyusunan Laporan Tahunan Inventaris BMN',
  'PL.540 - Sensus BMN',
  'PL.600 - PENYIMPANAN',
  'PL.610 - Penatausahaan Penyimpanan Barang/Publikasi:',
  'PL.611 - Tanda terima/ surat pengantar / surat pengiriman barang',
  'PL.612 - Surat Pernyataan harga dan mutu barang',
  'PL.613 - Berita Acara pengadaan',
  'PL.614 - Buku Penerimaan',
  'PL.615 - Buku Persediaan barang/kartu stock barang',
  'PL.616 - Kartu barang/ kartu gudang',
  'PL.620 - Penyusunan Laporan persedian barang',
  'PL.700 - PENYALURAN',
  'PL.710 - Penatausahaan penyaluran barang/ publikasi',
  'PL.711 - Surat Permintaan dari unit kerja/ formulir permintaan',
  'PL.712 - Surat Perintah Mengeluarkan Barang (SPMB)',
  'PL.713 - Surat Perintah Mengeluarkan barang Inventaris',
  'PL.714 - Berita Acara Serah terima Distribusi Barang',
  'PL.800 - PENGHAPUSAN BMN',
  'PL.810 - Penghapusan Barang Bergerak/Barang Inventaris Kantor: - Nota usulan penghapusan - Surat pembentukan panitia penghapusan - Berita Acara pemeriksaan/penelitian barang yang akan dihapus - Surat Izin/keputusan penghapusan barang - Surat Keputusan Panitia Lelang - Risalah lelang - Berita Acara dan laporan Tindak Lanjut Penghapusan ',
  'PL.900 - BUKTI-BUKTI KEPEMILIKAN DAN KELENGKAPAN BMN: a. Master Plan Bangunan b. Sertifikat Tanah c. Ijin Mendidirkan Bangunan (IMB) d. Bukti Kepemilikan Kendaraan Bermotor (BPKB) e. Surat Tanda Nomor Kendaraan (STNK) f. Denah/Gambar bangunan/Instalasi Listrik, Air dan  Gas ',
  'DL - PENDIDIKAN DAN LATIHAN',
  'DL.000 - PERENCANAAN DIKLAT',
  'DL.010 - Analisa Kebutuhan Penyelenggaraan Diklat.',
  'DL.020 - Sistem dan Metode.',
  'DL.030 - Kurikulum.',
  'DL.040 - Bahan Ajar/ Modul.',
  'DL.050 - Konsultasi Penyelenggaraan Diklat.',
  'DL.100 - AKREDITASI LEMBAGA DIKLAT',
  'DL.110 - Surat Permohonan Akreditas·i',
  'DL.120 - Laporan Hasil Verifikasi Lapangan',
  'DL.130 - Berita Acara Rapat Verifikasi',
  'DL.140 - Berita Acara Rapat Tim Penilai',
  'DL.150 - Surat Keputusan Penetapan Akreditasi',
  'DL.160 - Sertifikat Akreditasi',
  'DL.170 - Laporan Akreditasi Lembaga Diklat',
  'DL.200 - PENYELENGGARAAN DIKLAT',
  'DL.210 - Prajabatan.',
  'DL.220 - Kepemimpinan.',
  'DL.230 - Teknis.',
  'DL.240 - Fungsional.',
  'DL.250 - Evaluasi Pasca Diklat.',
  'DL.300 - SERTIFIKASI SUMBERDAYA MANUSIA KEDIKLATAN - Naskah-naskah yang berkaitan dengan kegiatan sertifikasi sumberdaya kediklatan.',
  'DL.400 - SISTEM INFORMASI DIKLAT',
  'DL.410 - Data Lembaga Diklat.',
  'DL.420 - Data Prasarana Diklat.',
  'DL.430 - Data Sarana Diklat.',
  'DL.440 - Data Pengelola Diklat.',
  'DL.450 - Data Penyelenggara Diklat.',
  'DL.460 - Data Widyaiswara.',
  'DL.470 - Data Program Diklat.',
  'DL.500 - REGISTRASI SERTIFIKASI/STTPL Peserta Diklat',
  'DL.510 - Surat Permohonan Kode Registrasi.',
  'DL.520 - Buku Registrasi.',
  'DL.530 - Surat Penyampaian Kode Registrasi.',
  'DL.600 - EVALUASI PENYELENGGARAAN DIKLAT',
  'DL.610 - Evaluasi Materi Penyelenggaraan.',
  'DL.620 - Evaluasi Pengajar / Instruktur / Fasilitator.',
  'DL.630 - Evaluasi Peserta.',
  'DL.640 - Evaluasi Sarana dan Prasarana.',
  'DL.650 - Evaluasi Alumni Peserta.',
  'DL.660 - Laporan Penyelenggaran.',
  'DL.670 - Evaluasi Alumni Diklat',
  'PK - KEPUSTAKAAN',
  'PK.000 - PENYIMPANAN DEPOSIT BAHAN PUSTAKA',
  'PK.010 - Bukti Penerimaan Koleksi Bahan Pustaka Deposit.',
  'PK.020 - Administrasi Pengolahan Deposit Bahan Pustaka.',
  'PK.100 - PENGADMN BAHAN PUSTAKA',
  'PK.110 - Buku Induk Koleksi.',
  'PK.120 - Daftar Buku Terseleksi.',
  'PK.130 - Daftar Buku Dalam Pemesanan.',
  'PK.140 - Daftar Buku Dalam Permintaan.',
  'PK.200 - PENGOLAHAN BAHAN PUSTAKA',
  'PK.210 - Lembar Kerja Pengolahan Bahan Pustaka (buram, pengkatalogan).',
  'PK.220 - Shell List/Jajaran Kartu Utama (master list).',
  'PK.230 - Daftar Tambahan Buku (assesion list).',
  'PK.240 - Daftar/Jajaran Kendali (subjek dan pengarang).',
  'PK.300 - LAYANAN JASA PERPUSTAKAAN DAN INFORMASI',
  'PK.310 - Data dan statistik anggota, pengunjung dan peminjaman bahan pustaka.',
  'PK.320 - Pertanyaan, Rujukan dan Jawaban.',
  'PK.400 - PRESERVASIBAHANPUSTAKA',
  'PK.410 - Survei Kondisi Bahan Pustaka.',
  'PK.420 - Reprografi Bahan Pustaka.',
  'PK.500 - PEMBINAAN PERPUSTAKAAN',
  'PK.510 - Bimbingan Teknis.',
  'PK.520 - Penyuluhan.',
  'PK.530 - Sosialisasi.',
  'IF - INFORMATIKA',
  'IF.000 - RENCANA STRATEGIS MASTERPLAN PEMBANGUNAN SISTEM INFORMASI',
  'IF.100 - DOKUMENTASI ARSITEKTUR',
  'IF.110 - Sistem lnformasi.',
  'IF.120 - Sistem Aplikasi.',
  'IF.130 - Infrastruktur.',
  'IF.200 - PEREKAMAN DAN PEMUTAKHIRAN DATA',
  'IF.210 - Formulir Isian.',
  'IF.220 - Daftar Petugas Perekaman.',
  'IF.230 - Jadwal Pelaksanaan.',
  'IF.240 - Laporan Hasil Perekaman dan Pemutakhiran Data.',
  'IF.300 - MIGRASI SISTEM APLIKASI DATA',
  'IF.400 - DOKUMEN HOSTING',
  'IF.410 - Formulir Permintaan Hosting.',
  'IF.420 - Layanan Hasil Uji Kelayakan.',
  'IF.430 - Laporan Pelaksanaan Hosting.',
  'IF.500 - LAYANAN BACK-UP DATA DIGITAL',
  'PW - PENGAWASAN',
  'PW.000 - RENCANA PENGAWASAN',
  'PW.010 - Rencana Strategis Pengawasan.',
  'PW.020 - Rencana Kerja Tahunan.',
  'PW.030 - Rencana Kinerja Tahunan.',
  'PW.040 - Penetapan Kinerja Tahunan.',
  'PW.050 - Rakor Pengawasan Tingkat Nasional.',
  'PW.100 - PELAKSANAAN PENGAWASAN',
  'PW.110 - Naskah-naskah yang berkaitan dengan audit mulai dari surat penugasan sampai dengan surat menyurat.',
  'PW.120 - Laporan Hasil Audit (LHA), Laporan Hasil Pemeriksaaan Operasional (LHPO), Laporan Hasil Evaluasi (LHE), Laporan Akuntan (LA), Laporan Auditor Independent (LAI) yang memerlukan Tindak Lanjut (TL).',
  'PW.130 - Laporan Hasil Audit Investigasi (LHAI) yang mengandung unsur Tindak Pidana Korupsi (TPK) dan memerlukan tindak lanjut.',
  'PW.140 - Laporan Perkembangan Penanganan Surat Pengaduan Masyarakat.',
  'PW.150 - Laporan Pemutakhiran Data.',
  'PW.160 - Laporan Perkembangan BMN.',
  'PW.170 - Laporan kegiatan pendampingan penyusunan laporan keuangan dan Reviu Departmen/LPND.',
  'PW.180 - Good Corporate Governance (GCG).',
  'TS - TRANSFORMASI STATISTIK',
  'TS.000 - PENYUSUNAN RENCANA KEGIATAN BIDANG TRANSFORMASI STATISTIK (TOR)',
  'TS.010 - Transformasi Proses Bisnis Statistik.',
  'TS.020 - Transformasi TIK dan  Komunikasi.',
  'TS.030 - Transformasi Manajemen Sumberdaya Manusia dan Kelembagaan.',
  'TS.100 - PENYUSUNAN BAHAN TERKAIT TRANSFORMASI STATISTIK',
  'TS.110 - Rencana Sarana dan Prasarana Transformasi Statistik.',
  'TS.120 - Statistical Busines Frame Work and Architecture (SBFA).',
  'TS.130 - Analysis Document.',
  'TS.140 - CSL',
  'TS.150 - BPR.',
  'TS.160 - Sosialisasi, internalisasi, workshop terkait kegiatan transformasi.',
  'TS.170 - Deliverables.',
  'TS.200 - MANAJEMEN PERUBAHAN',
  'TS.210 - Steering Committee (Dewan Pengarah).',
  'TS.220 - Change Agent.',
  'TS.230 - Change Leader.',
  'TS.240 - Change Champion.',
  'TS.250 - Working Group.',
  'TS.260 - Evaluasi dan Monitoring Perkembangan Program STATCAP CERDAS; Sensus Daring/CPOC.',
  'TS.270 - Sosialisasi, Internalisasi, Workshop terkait kegiatan Manajemen Perubahan, Kick of Meeting.',
  'TS.300 - KETERPADUAN TRANSFORMASI',
  'TS.310 - Mendukung lmplementasi Transformasi: CAPI SAKERNAS, Continous Survey.',
  'TS.400 - LAPORAN TRANSFORMASI STATISTIK',
  'TS.410 - Laporan Kemajuan.',
  'TS.420 - Laporan Bulanan.',
  'TS.430 - Laporan Triwulanan.',
  'TS.440 - Laporan Tahunan.'
]

let tree = {}
let kode1 = ''
data.forEach(k => {
  let kode0 = k.substring(0, 2)
  if (!tree[kode0]) {
    tree[kode0] = {
      value: k,
      title: k
    }
  } else {
    if(kode1 === '9' && kode0 === 'HK') kode1 = '10'
    else {
      if(kode1 === '10' && kode0 === 'HK') kode1 = '10'
      else kode1 = k.substring(3, 4)
    }
    if (!tree[kode0][kode1]) {
      tree[kode0][kode1] = {
        value: k,
        title: k
      }
    } else {
      let kode2 = k.substring(4, 5)
      if(kode1 === '10') kode2 = k.substring(5, 6)
      if (!tree[kode0][kode1][kode2]) {
        tree[kode0][kode1][kode2] = {
          value: k,
          title: k
        }
      } else {
        let kode3 = k.substring(5, 6)
        if(kode1 === '10') kode3 = k.substring(7, 8)
        tree[kode0][kode1][kode2][kode3] = {
          value: k,
          title: k
        }
      }
    }
  }
});

let tree_ok = []
let i0 = 0
let i1 = 0
let i2 = 0
for (const key0 in tree) {
  if (Object.hasOwnProperty.call(tree, key0)) {
    i0 += 1
    i1 = 0
    tree_ok.push({
      value: tree[key0].value,
      title: tree[key0].title,
      selectable: false,
    })

    for (const key1 in tree[key0]) {
      if (Object.hasOwnProperty.call(tree[key0], key1) && key1 !== 'value' && key1 !== 'title') {
        if(!tree_ok[i0-1].children) {
          tree_ok[i0-1].children = []
        }
        i1 += 1
        i2 = 0
        tree_ok[i0-1].children.push({
          value: tree[key0][key1].value,
          title: tree[key0][key1].title,
        })

        for (const key2 in tree[key0][key1]) {
          if (Object.hasOwnProperty.call(tree[key0][key1], key2) && key2 !== 'value' && key2 !== 'title') {
            if(!tree_ok[i0-1].children[i1-1].children) {
              tree_ok[i0-1].children[i1-1].children = []
            }
            i2 += 1
            tree_ok[i0-1].children[i1-1].children.push({
              value: tree[key0][key1][key2].value,
              title: tree[key0][key1][key2].title,
            })
          }
        }
      }
    }
  }
}

module.exports = tree_ok